# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6501c1d8b777079727ff8aeef4999257c9f53b4212b70567226f93d2a07b6cce54463c7ed9dd004b13d87e4e9803044225eca2eda001dd3661a19fc3be1f61cc

test:
  secret_key_base: 2251f4f52235dc58ea68ade71b014611f4e5e7157d350d4830d79d5551a237944ed61392447c23eb2fd75471ab2018cef7d09a62269a671923e1a64a00fde6f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
